{
 "title": "Temporal server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Matcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Matcher poll",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(poll_success_sync[5m])) ",
     "legendFormat": "Success sync"
    },
    {
     "expr": "sum by (operation) (rate(poll_success[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (operation) (rate(poll_timeouts[5m]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(rate(sync_throttle_count[5m]))",
     "legendFormat": "Sync_Throttle"
    }
   ]
  },
  {
   "title": "Matcher poll",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (domain) (rate(poll_success_sync{app=\"cadence-matching\"}[5m]))",
     "legendFormat": "Success sync: {{domain}}"
    },
    {
     "expr": " sum by (domain) (rate(poll_success{app=\"cadence-matching\"}[5m]))",
     "legendFormat": "Success: {{domain}}"
    },
    {
     "expr": " sum by (domain) (rate(poll_timeouts{app=\"cadence-matching\"}[5m]))",
     "legendFormat": "Timeout: {{domain}}"
    },
    {
     "expr": "sum(rate(sync_throttle_count[5m]))",
     "legendFormat": "Sync_Throttle"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "frontend latency by operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cadence_latency_sum{kubernetes_namespace=~\"[[namespace]]\",app=\"cadence-frontend\",operation!~\"PollForActivityTask|PollForDecisionTask\"}[5m]) / rate(cadence_latency_count{kubernetes_namespace=~\"[[namespace]]\",app=\"cadence-frontend\",operation!~\"PollForActivityTask|PollForDecisionTask\"}[5m])) by (kubernetes_namespace,app,operation)"
    }
   ]
  },
  {
   "title": "cadence requests frontend by operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(cadence_requests{kubernetes_namespace=~\"[[namespace]]\",app=\"cadence-frontend\",operation!~\"PollForActivityTask|PollForDecisionTask\"}[5m]))"
    }
   ]
  },
  {
   "title": "Match latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Match sync\\async rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation, kubernetes_namespace) (rate(syncmatch_latency_count{kubernetes_namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "sync-{{operation}}"
    },
    {
     "expr": "sum by (operation, kubernetes_namespace) (rate(asyncmatch_latency_count{kubernetes_namespace=\"$namespace\"}[1m])) * -1",
     "legendFormat": "async-{{operation}}"
    }
   ]
  },
  {
   "title": "persistence latency rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(persistence_latency_sum{operation=\"CreateWorkflowExecution\"}[1m])"
    }
   ]
  },
  {
   "title": "Task latency 0.99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(task_latency_bucket{kubernetes_namespace=~\"[[namespace]]\"}[5m])) by (operation,le))"
    }
   ]
  },
  {
   "title": "Task requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(task_requests[1m]))"
    }
   ]
  },
  {
   "title": "persistence latency by operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(persistence_latency_bucket{kubernetes_namespace=~\"[[namespace]]\"}[5m])) by (operation,le))"
    }
   ]
  },
  {
   "title": "persistence requests rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(persistence_requests{operation=\"CreateTask\"}[1m]))",
     "legendFormat": "operation=\"CreateTask\""
    }
   ]
  }
 ]
}