{
 "title": "Temporal",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Temporal frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflow total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_workflow_completed_total[5m])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "rate(temporal_workflow_failed_total[5m])-1",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg  latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_PollForActivityTask_temporal_latency_seconds_sum[5m]) / rate(temporal_PollForActivityTask_temporal_latency_seconds_count[5m])",
     "legendFormat": "{{TaskList}}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Active thread count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "temporal_workflow_active_thread_count",
     "legendFormat": "{{TaskList}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Workflow complete rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_workflow_completed_total[5m])"
    }
   ]
  },
  {
   "title": "Activity poll total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_activity_poll_total_total[5m])"
    }
   ]
  },
  {
   "title": "Decision poll total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_decision_poll_total_total[5m])"
    }
   ]
  }
 ]
}