server:
  port: 8097

management.endpoint.metrics.enabled: 'true'
management.endpoint.prometheus.enabled: 'true'
management.endpoint.health.enabled: 'true'
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: '*'
management.metrics.export.prometheus.enabled: 'true'